[[card]]
id = 102345678
ot = "custom"
alias = 10000000
name = "Obelisk the Tormentor"
attribute = "divine"
race = "divine-beast"
type = "monster effect"
atk = 4000
def = 4000
level = 10
effect = '''
Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. This card is unaffected by your opponent's card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls.'''
year = 2025
author = "Maniak"

[[card]]
id = 102345679
ot = "custom"
alias = 10000020
name = "Slifer the Sky Dragon"
attribute = "divine"
race = "divine-beast"
type = "monster effect"
atk = "?"
def = "?"
level = 10
effect = '''
Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. This card is unaffected by your opponent's card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. Gains 1000 ATK/DEF for each card in your hand. If a monster(s) is Normal or Special Summoned to your opponent's field: That monster(s) loses 2000 DEF, then if its DEF has been reduced to 0 as a result, destroy it.'''
year = 2025
author = "Maniak"

[[card]]
id = 102345680
ot = "custom"
alias = 10000010
name = "The Winged Dragon of Ra"
attribute = "divine"
race = "divine-beast"
type = "monster effect"
atk = "?"
def = "?"
level = 10
effect = '''
Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. This card is unaffected by your opponent's card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. This card's ATK/DEF are equal to the combined ATK/DEF of the Tributes. When this card is Special Summoned: You can pay LP so that you have 100 left; this card gains ATK/DEF equal to the amount of LP paid. You can pay 1000 LP, then target 1 monster on the field; destroy that target.'''
year = 2025
author = "Maniak"